# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATD_ATENDIMENTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATD_DTHR_INICIO', models.DateTimeField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 917178, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='CHA_CHAMADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHA_DT_ABERTURA', models.DateField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 915316, tzinfo=utc))),
                ('CHA_ASSUNTO', models.CharField(max_length=255)),
                ('CHA_MENSAGEM', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EMP_EMPRESA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_NOME_FANTASIA', models.CharField(max_length=80)),
                ('EMP_RAZAO_SOCIAL', models.CharField(max_length=80)),
                ('EMP_NR_CNPJ', models.CharField(max_length=14)),
                ('EMP_LOGRADOURO', models.CharField(max_length=255)),
                ('EMP_NR_LOGRADOURO', models.CharField(max_length=255)),
                ('EMP_CIDADE', models.CharField(max_length=100)),
                ('EMP_UF', models.CharField(max_length=2)),
                ('EMP_PAIS', models.CharField(max_length=100)),
                ('EMP_TELEFONE', models.CharField(max_length=11)),
                ('EMP_EMAIL', models.EmailField(max_length=100)),
                ('EMP_NOME_RESPONSAVEL', models.CharField(max_length=80)),
                ('EMP_CARGO_RESPONSAVEL', models.CharField(max_length=45)),
                ('EMP_CPF_RESPONSAVEL', models.CharField(max_length=11)),
                ('EMP_DT_ABERTURA', models.DateField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 911421, tzinfo=utc))),
                ('EMP_DT_ATIVACAO', models.DateField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 911478, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PFL_PERFIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PFL_NOME', models.CharField(max_length=80)),
                ('PFL_DESCRICAO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RMO_RAMO_ATIVIDADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RMO_NOME', models.CharField(max_length=45)),
                ('STS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RMO_RAMO_ATIVIDADE')),
            ],
        ),
        migrations.CreateModel(
            name='STS_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STS_NOME', models.CharField(max_length=45)),
                ('STS_DESCRICAO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SVC_SERVICO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SVC_NOME', models.CharField(max_length=45)),
                ('SVC_DESCRICAO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TCK_TICKET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TCK_DT_EMISSAO', models.DateField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 916306, tzinfo=utc))),
                ('TCK_HR_EMISSAO', models.TimeField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 916345, tzinfo=utc))),
                ('EMP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EMP_EMPRESA')),
                ('SVC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SVC_SERVICO')),
            ],
        ),
        migrations.CreateModel(
            name='USU_USUARIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USU_NOME', models.CharField(max_length=80)),
                ('USU_EMAIL', models.EmailField(max_length=100)),
                ('USU_LOGIN', models.CharField(max_length=45)),
                ('USU_SENHA', models.CharField(max_length=45)),
                ('USU_DT_ATIVACAO', models.DateField(default=datetime.datetime(2016, 6, 6, 18, 50, 52, 913477, tzinfo=utc))),
                ('EMP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.EMP_EMPRESA')),
                ('PFL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PFL_PERFIL')),
                ('STS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RMO_RAMO_ATIVIDADE')),
            ],
        ),
        migrations.AddField(
            model_name='emp_empresa',
            name='RMO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.STS_STATUS'),
        ),
        migrations.AddField(
            model_name='emp_empresa',
            name='STS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RMO_RAMO_ATIVIDADE'),
        ),
        migrations.AddField(
            model_name='cha_chamado',
            name='STS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.STS_STATUS'),
        ),
        migrations.AddField(
            model_name='cha_chamado',
            name='USU_ID_ABERTURA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.USU_USUARIO'),
        ),
        migrations.AddField(
            model_name='atd_atendimento',
            name='STS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.STS_STATUS'),
        ),
        migrations.AddField(
            model_name='atd_atendimento',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.USU_USUARIO'),
        ),
    ]
