# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='usuario_id_abertura',
            new_name='usuario_abertura',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='ramo_atividade_id',
            new_name='ramo_atividade',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='servico_id',
            new_name='servico',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='empresa_id',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='perfil_id',
            new_name='perfil',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ramo_atividade_id',
            new_name='ramo_atividade',
        ),
        migrations.RemoveField(
            model_name='ramoatividade',
            name='ramo_atividade_id',
        ),
        migrations.AddField(
            model_name='ramoatividade',
            name='status',
            field=models.ForeignKey(default=datetime.datetime(2016, 6, 18, 19, 19, 17, 201945, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
            preserve_default=False,
        ),
    ]
