# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 16:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tck_ticket',
            name='TCK_DT_EMISSAO',
        ),
        migrations.RemoveField(
            model_name='tck_ticket',
            name='TCK_HR_EMISSAO',
        ),
        migrations.AddField(
            model_name='tck_ticket',
            name='TCK_DTHR_EMISSAO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 63967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atd_atendimento',
            name='ATD_DTHR_INICIO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 64804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cha_chamado',
            name='CHA_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 62995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 58968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 59029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usu_usuario',
            name='USU_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 16, 32, 6, 61085, tzinfo=utc)),
        ),
    ]
