# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160607_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atd_atendimento',
            name='ATD_DTHR_INICIO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 996365, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cha_chamado',
            name='CHA_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 994575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 990675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 990743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tck_ticket',
            name='TCK_DTHR_EMISSAO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 995555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usu_usuario',
            name='USU_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 9, 43, 992578, tzinfo=utc)),
        ),
    ]
