# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160607_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tck_ticket',
            name='TCK_CD_ACESSO',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 18, 55, 56, 52872, tzinfo=utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tck_ticket',
            name='TCK_NR_TICKET',
            field=models.IntegerField(default=datetime.datetime(2016, 6, 7, 18, 56, 9, 977755, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atd_atendimento',
            name='ATD_DTHR_INICIO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 132952, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cha_chamado',
            name='CHA_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 131065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ABERTURA',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 127163, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 127215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tck_ticket',
            name='SVC_ID',
            field=models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='home.SVC_SERVICO'),
        ),
        migrations.AlterField(
            model_name='tck_ticket',
            name='TCK_DTHR_EMISSAO',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 132080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usu_usuario',
            name='USU_DT_ATIVACAO',
            field=models.DateField(default=datetime.datetime(2016, 6, 7, 18, 55, 49, 129055, tzinfo=utc)),
        ),
    ]
