# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160620_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
    ]
