# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160607_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 263774, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 262272, tzinfo=utc))),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('razao_social', models.CharField(max_length=80)),
                ('nr_cnpj', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=255)),
                ('nr_logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=80)),
                ('cargo_responsavel', models.CharField(max_length=45)),
                ('cpf_responsavel', models.CharField(max_length=11)),
                ('data_abertura', models.DateField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 257769, tzinfo=utc))),
                ('data_ativacao', models.DateField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 258269, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RamoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('ramo_atividade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('ramo_atividade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_ticket', models.IntegerField()),
                ('data_hora_emissao', models.DateTimeField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 263273, tzinfo=utc))),
                ('cd_acesso', models.CharField(max_length=8)),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Empresa')),
                ('servico_id', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='home.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('login', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=45)),
                ('data_ativacao', models.DateField(default=datetime.datetime(2016, 6, 10, 22, 54, 28, 259770, tzinfo=utc))),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Empresa')),
                ('perfil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Perfil')),
                ('ramo_atividade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade')),
            ],
        ),
        migrations.RemoveField(
            model_name='atd_atendimento',
            name='STS_ID',
        ),
        migrations.RemoveField(
            model_name='atd_atendimento',
            name='USU_ID',
        ),
        migrations.RemoveField(
            model_name='cha_chamado',
            name='STS_ID',
        ),
        migrations.RemoveField(
            model_name='cha_chamado',
            name='USU_ID_ABERTURA',
        ),
        migrations.RemoveField(
            model_name='emp_empresa',
            name='RMO_ID',
        ),
        migrations.RemoveField(
            model_name='emp_empresa',
            name='STS_ID',
        ),
        migrations.RemoveField(
            model_name='rmo_ramo_atividade',
            name='STS_ID',
        ),
        migrations.RemoveField(
            model_name='svc_servico',
            name='RMO_ID',
        ),
        migrations.RemoveField(
            model_name='tck_ticket',
            name='EMP_ID',
        ),
        migrations.RemoveField(
            model_name='tck_ticket',
            name='SVC_ID',
        ),
        migrations.RemoveField(
            model_name='usu_usuario',
            name='EMP_ID',
        ),
        migrations.RemoveField(
            model_name='usu_usuario',
            name='PFL_ID',
        ),
        migrations.RemoveField(
            model_name='usu_usuario',
            name='STS_ID',
        ),
        migrations.DeleteModel(
            name='ATD_ATENDIMENTO',
        ),
        migrations.DeleteModel(
            name='CHA_CHAMADO',
        ),
        migrations.DeleteModel(
            name='EMP_EMPRESA',
        ),
        migrations.DeleteModel(
            name='PFL_PERFIL',
        ),
        migrations.DeleteModel(
            name='RMO_RAMO_ATIVIDADE',
        ),
        migrations.DeleteModel(
            name='STS_STATUS',
        ),
        migrations.DeleteModel(
            name='SVC_SERVICO',
        ),
        migrations.DeleteModel(
            name='TCK_TICKET',
        ),
        migrations.DeleteModel(
            name='USU_USUARIO',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ramo_atividade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario_id_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
    ]
