# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160607_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atd_atendimento',
            name='ATD_DTHR_INICIO',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 222177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cha_chamado',
            name='CHA_DT_ABERTURA',
            field=models.DateField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 220056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ABERTURA',
            field=models.DateField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 216104, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emp_empresa',
            name='EMP_DT_ATIVACAO',
            field=models.DateField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 216158, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tck_ticket',
            name='TCK_DTHR_EMISSAO',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 221182, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usu_usuario',
            name='USU_DT_ATIVACAO',
            field=models.DateField(verbose_name=datetime.datetime(2016, 6, 9, 15, 53, 0, 218055, tzinfo=utc)),
        ),
    ]
