# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160620_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='sigla',
            field=models.CharField(default=datetime.datetime(2016, 6, 22, 2, 42, 23, 287738, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
