# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160621_0129'),
        ('home', '0009_servico_sigla'),
    ]

    operations = [
    ]
