# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(default=datetime.date.today)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=80)),
                ('razao_social', models.CharField(max_length=80)),
                ('nr_cnpj', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=255)),
                ('nr_logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=80)),
                ('cargo_responsavel', models.CharField(max_length=45)),
                ('cpf_responsavel', models.CharField(max_length=11)),
                ('data_abertura', models.DateField(default=datetime.date.today)),
                ('data_ativacao', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RamoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
                ('sigla', models.CharField(max_length=2)),
                ('ramo_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_ticket', models.IntegerField()),
                ('data_hora_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cd_acesso', models.CharField(max_length=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Empresa')),
                ('servico', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, to='home.Servico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('data_ativacao', models.DateField(default=datetime.date.today)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Empresa')),
                ('perfil', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Perfil')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Status')),
            ],
        ),
        migrations.AddField(
            model_name='ramoatividade',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ramo_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RamoAtividade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario_abertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
    ]
