# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160618_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(default=datetime.datetime(2016, 6, 19, 5, 39, 16, 664280, tzinfo=utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
    ]
