# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160619_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(default=datetime.datetime(2016, 6, 19, 6, 15, 3, 708641, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
