# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_empresa_bairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ramo_atividade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Status'),
        ),
    ]
