# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160620_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.Perfil'),
        ),
    ]
